<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<RootNamespace>Tharga.Console</RootNamespace>
		<Authors>Daniel Bohlin</Authors>
		<Company>Thargelion AB</Company>
		<Product>Tharga Console Speech</Product>
		<PackageTags>console poc posh powershell speech</PackageTags>
		<PackageIconUrl>https://thargelion.net/assets/component-console.png</PackageIconUrl>
		<RepositoryUrl>https://github.com/poxet/tharga-console.git</RepositoryUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageProjectUrl>https://github.com/Tharga/Console</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>1701;1702;CS1591;CA1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Speech" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Tharga.Console\Tharga.Console.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>