trigger:
- master

name: 3.5.$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BQC.ForceNewBaseline: false

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build and Test

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8'
      inputs:
        version: 8.0.x
        includePreviewVersions: false

    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      displayName: 'Restore nuget packages'
      inputs:
        command: 'restore'
        projects: '**/Tharga.Console*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/Tharga.Console*.csproj'
        arguments: '-c Release /p:NoWarn=0618'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/Tharga.Console*.Tests.csproj'
        arguments: '--collect "Code coverage" --configuration $(buildConfiguration) --filter "Category!=Database"'

    #- task: BuildQualityChecks@8
    #  displayName: 'Build Quality Checks'
    #  inputs:
    #    checkWarnings: true
    #    warningFailOption: 'build'
    #    allowWarningVariance: true
    #    warningVariance: '1'
    #    checkCoverage: true
    #    coverageFailOption: 'build'
    #    coverageType: 'blocks'
    #    allowCoverageVariance: true
    #    coverageVariance: '1'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Console.Standard'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Console.Standard.csproj'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Console'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Console.csproj'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Console.Speech'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Console.Speech.csproj'
        versioningScheme: 'byBuildNumber'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Release
  displayName: Release
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - job: Release
    displayName: Release

    steps:
    - download: current
      artifact: drop
    - checkout: self
      persistCredentials: true

    - task: NuGetCommand@2
      displayName: 'Push nuget packages to nuget.org'
      inputs:
        command: 'push'
        packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget.org'

    - script: |
         git tag $(Build.BuildNumber)
         git push origin $(Build.BuildNumber)
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Tag
